source 'http://rubygems.org'
gem 'cucumber'
gem 'debase', '~> 0.2.1'
gem 'faker', '~> 1.6', '>= 1.6.3'
gem 'faraday'
gem 'nokogiri', '~> 1.6', '>= 1.6.8'
gem 'page-object'
gem 'retries'
gem 'rspec'
gem 'ruby-debug-ide', '~> 0.6.0'
gem 'selenium-webdriver'
gem 'test-unit'